# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ĐOÀN Trần Công Danh - A Software Developer
email: congdanhqx@live.com
description: > # this means to ignore newlines until "baseurl:"
  Just something I don't want to forget. Something about programing, especially
  C++ stuff. Some stupid stuff should also be expected to appear here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://congdanhqx.github.io" # the base hostname & protocol for your site
twitter_username: congdanhqx
github_username:  congdanhqx
comments: true

# Build settings
markdown: kramdown

defaults:
  -
    values:
      comments: true
